[package]
name = "perk_solver"
version = "0.1.0"
edition = "2021"
authors = ["Pieter Partous"]
description = "Finds optimal material combination for a given gizmo"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
approx = "0.5.1"
clap = { version = "4.0.23", features = ["derive"] }
colored = "2.0.0"
derive_more = "0.99.17"
itertools = "0.10.5"
lazy_static = "1.4.0"
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.87"
serde_with = "2.0.1"
smallvec = "1.10.0"
test-case = "2.2.2"
