[package]
name = "perk_solver"
version = "0.1.0"
edition = "2021"
authors = ["Pieter Partous"]
description = "Finds optimal material combination for a given gizmo"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.23", features = ["derive"] }
derive_more = "0.99.17"
itertools = "0.10.5"
